### ISSUE TITLE
HTML leaking into Esh's Mirror flavor text

### ISSUE THREAD

**Issue by slysherz** [xKynn/zana#1]
I've notice that when you link the [[Esh's Mirror]] item, there is some HTML text that shows up in the flavor text. Here's how it looks:

![zana bot esh's mirror image](https://cdn.discordapp.com/attachments/267659310325039105/480721664737542154/image.png)

I might have some free time in a few weeks and I can try to fix this myself, in case you don't have the chance until then.
Thanks a lot for your work with this extension, it is pretty cool : )

**Comment by xKynn** [comment]
Hey wow this was a while ago, been busy with moving recently, I'll try to take a look soon
Also seems as if help text has entered flavor

**Comment by slysherz** [comment]
I had some free time and went on looking into this. It turns out the the bug was actually into the wiki document - the help section was written inside the flavor text section (I've already submitted a fix suggestion there). This is the relevant part from the wiki answer:
```
{
    'flavour text': "She looked upon her reflection&lt;br /&gt;and trembled, and shook,&lt;br /&gt;until she was not what she saw.&lt;br /&gt;&lt;br /&gt;&lt;span class=&quot;text-color -help&quot;&gt;This item can be transformed with a [[Blessing of Esh]]&lt;/span&gt;",
    'help text': ""
}
```

It was a lot of fun : )
