### ISSUE TITLE
Zana Unable to Parse Some Uniques

### ISSUE THREAD

**Issue by IllianiReal** [xKynn/zana#19]
I've found that Zana struggles to parse certain (but not all) uniques.

Currently I've only been able to confirm Cold Iron Point. Trying to use [[Cold Iron Point]] or a pastebin where a build has this item equipped will result in parse failure.

The below is a build export where the only change has been to equip a CIP: https://pastebin.com/2YCdhTsr

**Comment by xKynn** [comment]
Fixed in https://github.com/xKynn/PoE.py/commit/f5f4745b12ff0d9bb452e3a95c96fd8c9ae61881
