### ISSUE TITLE
Pastebin import not working

### ISSUE THREAD

**Issue by kxc0re** [xKynn/zana#2]
Can't really tell you more than those i tried didnt work:

* https://pastebin.com/uMVfFFVR
* https://pastebin.com/vdt1KyZj
* https://pastebin.com/v8C5a5uW

I tried importing a character from my account to PoB and then exporting it to pastebin
charinfo works fine, pastebin-parsing doesnt

Some error-reaction would be nice

**Comment by xKynn** [comment]
Thanks so much for the report, I think I know what is messing it up, i might have to create an auto testing routine so i don't push updates that don't work.

**Comment by xKynn** [comment]
Fixed with xKynn/PoE.py@8192a7415c3655353e4b5d6d304613c24d034119
