### ISSUE TITLE
The fandom wiki is outdated, change to poewiki?

### ISSUE THREAD

**Issue by vklages** [xKynn/zana#25]
Basically what the title states. The fandom wiki is now two leagues behind, while poewiki is up to date. Is there a possibility that the bot will be adjusted and starts linking to poewiki?

**Comment by xKynn** [comment]
Hey! I actually just switched the backend to poewiki yesterday in https://github.com/xKynn/PoE.py/commit/0032c9004b5eb0beee9821ee0afc3f596cc30b46, seems as though I forgot to change the links that the bot sends though, I'll be doing that soon.

**Comment by vklages** [comment]
Awesome, thank you very much!

**Comment by xKynn** [comment]
Done in https://github.com/xKynn/zana/commit/e12f273158819358c19c190ee41b3f29fec7dc52. Thanks for your issue!
