### ISSUE TITLE
Fails on all pastebin links

### ISSUE THREAD

**Issue by Razunter** [xKynn/zana#3]
Pretty much all links that I feed to Zana fail with "There was an error with parsing your pastebin."
Example link: https://pastebin.com/G71SFkYJ

**Comment by xKynn** [comment]
Ill take a look, only issue im aware of is with incomplete pastebins missing items in slots currently and wiki messing up with not showing some gems in the item table

**Comment by xKynn** [comment]
Apparently PoB marks Two-Toned boots as having "Evasion/Energy Shield" in the base. Wiki uses the resistances to mark what image to use. PoB does the same for rings, so it's inconsistency. I wouldn't mind taking a look at other links that were not working.

**Comment by Razunter** [comment]
This one: https://pastebin.com/cBsLbM51
From old PoB version. Other links were variations of the previous build.

**Comment by xKynn** [comment]
Tested around 30+ pastebins.
Fixed in:
https://github.com/xKynn/zana/commit/b20761f3b15be4dc8da108b55a2fdb3ee0932079
https://github.com/xKynn/PoE.py/commit/1dd49baebfd8a8ca6f1bef8ed648884497bc9d98
