### ISSUE TITLE
[Feature Request] Flavour text wrapping

### ISSUE THREAD

**Issue by GonePh1shing** [xKynn/zana#4]
Flavour text on linked unique items currently renders on a single line. This results in reduced readability when viewed in Discord.

[Example here](https://i.imgur.com/RV1Z83Z.png); this was captured on a 1080p screen. Compare that to the [original image served by the bot](https://cdn.discordapp.com/attachments/582523192804114453/582529804788826122/image.png), and the difference is night and day.

Even when viewed zoomed in, it is less readable than it could be. If the rendered image was less wide, Discord would allow for a larger zoom that would result in the text being bigger on screen.

Wrapping the flavour text such that it is no wider than the widest mod on the item would fix this.

**Comment by xKynn** [comment]
It does actually wrap for a readable amount, iirc its 7 words per line. The issue with that one is the <\br> tag which didn't get replaced by a space allowing the string to be parsed literally as a single word.

**Comment by xKynn** [comment]
It's either splitting into lines at the br tags or 7 words I can't remember but it does do multiline

**Comment by xKynn** [comment]
handles br tag at https://github.com/xKynn/PoE.py/blob/master/poe/utils.py#L86 
I'll be adding support for the other tag soon
