### ISSUE TITLE
Divination cards fail to embed after around 20 locations

### ISSUE THREAD

**Issue by smt923** [xKynn/zana#5]
After somewhere around 20-25 locations (possibly due to the discord embed field limit) the cards fail to embed, giving a generic error about the attach files permission, even though other cards can embed fine:

![](https://i.imgur.com/Rm2CAVF.png)

Perhaps after around 5-10 locations it should be truncated as it starts to fill out the screen quite a bit anyway

**Comment by xKynn** [comment]
Fair point. Will add truncation for next patch, thanks for the report! I'm thinking it can only really be either all maps or a few tilesets.

**Comment by xKynn** [comment]
Fixed in https://github.com/xKynn/zana/commit/4eaebbc57cf8677a9f91824cb802ed838a9fc550.
