### ISSUE TITLE
Documentation and charinfo issues

### ISSUE THREAD

**Issue by Razunter** [xKynn/zana#6]
This is mostly about `@Zana help`:

> roll - Roll any Unique item and test your luck! 

This sounds like it should roll a random unique and not roll stats of a specific unique.

`@Zana help charinfo`:
> charinfo Fetch character info for provided account and character

Actually doesn't require account and has something called "garb"

---

Error messages like these are missing a command:
> The command only needs your character name in the format
> `@Zana <charname>` - continuing regardless

> The correct format to use roll is
> `@Zana <itemname>`

Should be `@Zana charinfo <charname>` (garb?!), `@Zana roll <itemname>`

---

Also for some reason this fails without any message: `@Zana charinfo KriXPelloR`
Profile: https://www.pathofexile.com/account/view-profile/KriXPello/characters

**Comment by xKynn** [comment]
Remedied in https://github.com/xKynn/zana/commit/ffb49037d699f6fb99af8fc9a8d09787c9536c8c
