### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'invoke'

### ISSUE THREAD

**Issue by VoxLight** [xKynn/zana#7]
Seems like the link command is throwing an error on this:

`self.bot.loop.create_task(self.link.invoke(ctx))` (line 129)

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\tkkt3\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\tkkt3\Desktop\Active Bots\zana-master\bot.py", line 58, in on_message
    await self.find_command.invoke(ctx)
AttributeError: 'NoneType' object has no attribute 'invoke'
```

**Comment by xKynn** [comment]
That would imply it had errors with finding the find "command". The bot requires a few additional setup steps that are as of now unlisted.

**Comment by xKynn** [comment]
If you join the support server, I can help with setting it up, but it's planned for it to be easier to setup later.
