### ISSUE TITLE
Zana not linking div cards/prophecies

### ISSUE THREAD

**Issue by VoxLight** [xKynn/zana#8]
So, I invited your bot to my testing server (an insanely cool concept I was really interested in messing around with). Unfortunately, it appears Zana is unable to link prophecies or divination cards. Trying to link [[The Doctor]] [[Fated Connections]] or [[The Plaguemaw II]] all end up with zana typing for 5 seconds, then not sending any message (Not even the "Item not found message" which works on other items.)

**Comment by xKynn** [comment]
Last patch broke a lot of things unfortunately I'm busy with exams and won't be able to fix until tomorrow.

**Comment by VoxLight** [comment]
> Last patch broke a lot of things unfortunately I'm busy with exams and won't be able to fix until tomorrow.

Good luck with your exams man. I'm right there with you, midterms are coming. I will peek around and see if I can't spot anything I might be able to make a pull request on. Was it the patch that you made? or the patch from GGG?

**Comment by xKynn** [comment]
Fixed in https://github.com/xKynn/PoE.py/commit/dab4d0a7502e47c40a2df03f9f87606ebcbf0a64
